### ISSUE TITLE
Travis is still broken

### ISSUE THREAD

**Issue by jchodera** [choderalab/assaytools#122]
There's an `icu` dependency issue now:
https://travis-ci.org/choderalab/assaytools/jobs/260750171#L1052-L1097
```
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 686, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 809, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 849, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - icu 58.1.*
```
However, `icu==58.1` does seem to be available via [`conda-forge`](https://anaconda.org/conda-forge/icu/files).

**Comment by jchodera** [comment]
This may be some sort of anaconda http error. Restarting builds...
