### ISSUE TITLE
xml2png python 3.6 travis tests are failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/assaytools#135]
The [python 3.6 travis tests are failing](https://travis-ci.org/choderalab/assaytools/jobs/458984948#L1697) for `xml2png`:
```
2.49s$ pushd . && cd examples/direct-fluorescence-assay/data && xml2png --type singlet_384 p38*.xml && popd
~/build/choderalab/assaytools ~/build/choderalab/assaytools
['p38_singlet1_20160420_153238.xml', 'p38_singlet2_20160420_154750.xml']
*** --type: analyzing singlet_384 file(s) ***
****This script is about to make png files for 2 xml files. ****
****The xml file p38_singlet1_20160420_153238.xml has 10 data sections:****
dict_keys(['280_480_TOP_100', '280_480_BOT_100', '280_480_TOP_120', '280_480_BOT_120', '340_480_TOP_100', '340_480_BOT_100', '340_480_TOP_120', '340_480_BOT_120', '280_340_TOP_100', '280_340_BOT_100'])
Traceback (most recent call last):
  File "/Users/travis/miniconda3/envs/test/bin/xml2png", line 11, in <module>
    sys.exit(entry_point())
  File "/Users/travis/miniconda3/envs/test/lib/python3.6/site-packages/assaytools/scripts/xml2png.py", line 489, in entry_point
    process_files_singlet(xml_files)
  File "/Users/travis/miniconda3/envs/test/lib/python3.6/site-packages/assaytools/scripts/xml2png.py", line 476, in process_files_singlet
    plot_singlet_one_section(data,key)
  File "/Users/travis/miniconda3/envs/test/lib/python3.6/site-packages/assaytools/scripts/xml2png.py", line 427, in plot_singlet_one_section
    axes[int(i/2)].set_color_cycle(['black','red'])
AttributeError: 'AxesSubplot' object has no attribute 'set_color_cycle'
```
This is easy to fix, and the python 3.5 tests give a deprecation warning that contains the solution:
```
/Users/travis/miniconda3/envs/test/lib/python3.5/site-packages/assaytools/scripts/xml2png.py:427: MatplotlibDeprecationWarning: 
The set_color_cycle function was deprecated in version 1.5. Use `.set_prop_cycle` instead.
```

**Comment by sonyahanson** [comment]
Think this was fixed here: https://github.com/choderalab/assaytools/pull/133/commits/9fdb55fb15562a6dc5b4b5ca8d49be89e05f7979
